# -*- coding: utf-8 -*-
"""COVID_INDIA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZZm_AkbZKfK5Q9fPYR-cOb2bVQuCxH07
"""

import numpy as np
import pandas as pd
import os
import io
import requests
import matplotlib.pyplot as plt
import seaborn as sns
import time
import datetime


s = pd.read_csv('countries-aggregated.csv',encoding='utf-8').fillna(0)
d = pd.read_csv('countries-aggregated.csv')
date = d['Date']


r = s['Recovered'].iloc[0:320].values
d = s['Deaths'].iloc[0:320].values
c = s['Confirmed'].iloc[0:320].values
a = s['Active'].iloc[0:320].values
dc = s['Daily New Cases'].iloc[0:320].values
dr = s['Daily New Recovered'].iloc[0:320].values
dd = s['Daily New Deaths'].iloc[0:320].values

class INDCovid:
    def __init__(self):
        from datetime import date
        self._today = date.today()
                
    def today(self):
        print("Today is:",self._today)
    
        
    def active(self):
        fig = plt.figure(figsize=(15,7))
        ax = fig.add_subplot(111)
        ax.set_title("Active cases")
        ax.set_xlabel('time')
        ax.set_ylabel('Active cases')
        #ax.set_xlim([0,5])
        ax.plot(date,a,label='Active')
        leg = ax.legend()
        plt.show()
        
    def confirmed(self):
        fig = plt.figure(figsize=(15,7))
        ax = fig.add_subplot(111)
        ax.set_title("Confirmed cases")
        ax.set_xlabel('time')
        ax.set_ylabel('Confirmed cases')
        #ax.set_xlim([0,5])
        ax.plot(date,c,label='confirmed')
        leg = ax.legend()
        plt.show()
        
    def deaths(self):
        fig = plt.figure(figsize=(15,7))
        ax = fig.add_subplot(111)
        ax.set_title("Deaths")
        ax.set_xlabel('time')
        ax.set_ylabel('Deaths')
        #ax.set_xlim([0,5])
        ax.plot(date,d,label='Deaths')
        leg = ax.legend()
        plt.show()
        
    def Recovered(self):
        fig = plt.figure(figsize=(15,7))
        ax = fig.add_subplot(111)
        ax.set_title("Recovered")
        ax.set_xlabel('time')
        ax.set_ylabel('Recovered')
        #ax.set_xlim([0,5])
        ax.plot(date,r,label='Recovered')
        leg = ax.legend()
        plt.show()

i = INDCovid()

i.today()

i.active()

i.confirmed()

i.deaths()

i.Recovered()



